steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - -c
    - |
      docker build -t northamerica-south1-docker.pkg.dev/store-microservices-459102/image-registry/orders-microservice -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_DATABASE_URL=$$ORDERS_DATABASE_URL .
  secretEnv: ['ORDERS_DATABASE_URL']

- name: 'gcr.io/cloud-builders/docker'
  args: 
    [
      'push',
       "northamerica-south1-docker.pkg.dev/store-microservices-459102/image-registry/orders-microservice",
    ]

availableSecrets:
  secretManager:
  - versionName: projects/54850362336/secrets/ORDERS_DATABASE_URL/versions/1
    env: 'ORDERS_DATABASE_URL'